name: analytics_cup_analyst
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.3
  - plotly=6.4.0
  - scipy=1.16.2
  - jupyter
  - notebook
  - pip
  - pip:
    - kloppy==3.15.0
    - mplsoccer==1.5.1
    - dash==3.3.0